version: 2

updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "release/2.0"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "release/1.4"