version: 2

project_name: hauler
before:
  hooks:
    - go mod tidy
    - go mod download
    - rm -rf cmd/hauler/binaries

release:
  prerelease: auto
  make_latest: false

env:
  - vpkg=github.com/rancherfederal/hauler/internal/version
  - cosign_version=v2.2.3+carbide.2

builds:
  - main: cmd/hauler/main.go
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X {{ .Env.vpkg }}.gitVersion={{ .Version }} -X {{ .Env.vpkg }}.gitCommit={{ .ShortCommit }} -X {{ .Env.vpkg }}.gitTreeState={{if .IsGitDirty}}dirty{{else}}clean{{end}} -X {{ .Env.vpkg }}.buildDate={{ .Date }}
    hooks:
      pre:
        - wget -P cmd/hauler/binaries/ https://github.com/hauler-dev/cosign/releases/download/{{ .Env.cosign_version }}/cosign-{{ .Os }}-{{ .Arch }}{{ if eq .Os "windows" }}.exe{{ end }}
    env:
      - CGO_ENABLED=0

universal_binaries:
  - replace: false

changelog:
  disable: false
  use: git

brews:
  - name: hauler
    repository:
      owner: hauler-dev
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    description: "Hauler CLI"
