project_name: hauler
before:
  hooks:
    - go mod tidy
builds:
  - main: cmd/haulerctl/main.go
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
