project_name: hauler
builds:
  - main: cmd/hauler/main.go
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

universal_binaries:
  - replace: true

brews:
  - name: hauler
    tap:
      owner: rancherfederal
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    folder: Formula
    description: "Hauler CLI"
