package flags

import (
	"context"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strconv"

	"github.com/docker/go-units"
	"github.com/spf13/cobra"
	"hauler.dev/go/hauler/v2/pkg/blob"
	"hauler.dev/go/hauler/v2/pkg/consts"
	"hauler.dev/go/hauler/v2/pkg/log"
	"hauler.dev/go/hauler/v2/pkg/store"
)

// storeIDPattern matches the full shape of a StoreID as generated by uuid.New()... e.g. "ec520cf6-e01b-4d6f-93ea-6588de0d5159"
// Short prefixes (e.g. "ec520cf6") are resolved by ResolveStoreID itself and never reach this pattern unless the lookup fails
var storeIDPattern = regexp.MustCompile(`^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$`)

type StoreRootOpts struct {
	StoreDir     string
	Retries      int
	TempOverride string

	// Large-blob parallel retrieval knobs. Empty/zero → env var → built-in default.
	Concurrency    int    // --concurrency
	ChunkThreshold string // --chunk-threshold (human size, e.g. "100MiB")
	ChunkSize      string // --chunk-size (human size, e.g. "32MiB")
}

func (o *StoreRootOpts) AddFlags(cmd *cobra.Command) {
	pf := cmd.PersistentFlags()
	pf.StringVarP(&o.StoreDir, "store", "s", "", "Set the directory to use for the content store")
	pf.IntVarP(&o.Retries, "retries", "r", consts.DefaultRetries, "Set the number of retries for operations")
	pf.StringVarP(&o.TempOverride, "tempdir", "t", "", "(Optional) Override the default temporary directory determined by the OS")
	pf.IntVar(&o.Concurrency, "concurrency", 0,
		"(Optional) Parallel connections per blob for large-blob retrieval (0 = default 10; 1 disables chunking)")
	pf.StringVar(&o.ChunkThreshold, "chunk-threshold", "",
		"(Optional) Minimum blob size to trigger parallel ranged retrieval, e.g. 100MiB (default 100MiB)")
	pf.StringVar(&o.ChunkSize, "chunk-size", "",
		"(Optional) Range window per parallel request, e.g. 8MiB (default 8MiB)")
}

// BlobOptions resolves large-blob retrieval settings with precedence
// flag > env var > built-in default, and returns the blob.Options to attach to
// the store.
func (o *StoreRootOpts) BlobOptions() (blob.Options, error) {
	opts := blob.DefaultOptions()

	// connections
	if o.Concurrency > 0 {
		opts.Connections = o.Concurrency
	} else if v := os.Getenv(consts.HaulerBlobConnections); v != "" {
		n, err := strconv.Atoi(v)
		if err != nil {
			return opts, fmt.Errorf("invalid %s=%q: %w", consts.HaulerBlobConnections, v, err)
		}
		opts.Connections = n
	}

	// chunk threshold
	if v := firstNonEmpty(o.ChunkThreshold, os.Getenv(consts.HaulerBlobChunkThreshold)); v != "" {
		n, err := units.RAMInBytes(v)
		if err != nil {
			return opts, fmt.Errorf("invalid chunk-threshold %q: %w", v, err)
		}
		opts.ChunkThreshold = n
	}

	// chunk size
	if v := firstNonEmpty(o.ChunkSize, os.Getenv(consts.HaulerBlobChunkSize)); v != "" {
		n, err := units.RAMInBytes(v)
		if err != nil {
			return opts, fmt.Errorf("invalid chunk-size %q: %w", v, err)
		}
		opts.ChunkSize = n
	}

	return opts, nil
}

// firstNonEmpty returns the flag value if set, else the env value.
func firstNonEmpty(flagVal, envVal string) string {
	if flagVal != "" {
		return flagVal
	}
	return envVal
}

func (o *StoreRootOpts) Store(ctx context.Context, ro *CliRootOpts) (*store.Layout, error) {
	l := log.FromContext(ctx)

	haulerDir := resolveHaulerDir(ro)

	storeDir := o.StoreDir

	if storeDir == "" {
		storeDir = os.Getenv(consts.HaulerStoreDir)
	}

	if storeDir == "" {
		storeDir = consts.DefaultStoreName
	}

	// If storeDir doesn't exist as a path, see if it's a StoreID registered from a previous run elsewhere
	if _, err := os.Stat(storeDir); errors.Is(err, os.ErrNotExist) {
		id, resolved, rerr := store.ResolveStoreID(haulerDir, storeDir)
		switch {
		case rerr == nil:
			if !store.MatchesStoreID(resolved, id) {
				return nil, fmt.Errorf("store id %q was last seen at %s, but that path no longer contains that store", storeDir, resolved)
			}
			l.Debugf("resolved store id [%s] to [%s]", storeDir, resolved)
			storeDir = resolved
		case storeIDPattern.MatchString(storeDir):
			// looks like an ID, not a directory name to create
			return nil, fmt.Errorf("no store found matching id %q (for directories, use the absolute path)", storeDir)
		}
	}

	abs, err := filepath.Abs(storeDir)
	if err != nil {
		return nil, err
	}

	o.StoreDir = abs

	l.Debugf("using store at [%s]", abs)

	if _, err := os.Stat(abs); errors.Is(err, os.ErrNotExist) {
		if err := os.MkdirAll(abs, os.ModePerm); err != nil {
			return nil, err
		}
	} else if err != nil {
		return nil, err
	}

	s, err := store.NewLayout(abs, store.WithHaulerDir(haulerDir))
	if err != nil {
		return nil, err
	}
	l.Debugf("generated store id of [%s]", s.StoreID)

	bo, err := o.BlobOptions()
	if err != nil {
		return nil, err
	}
	s.BlobOpts = bo

	return s, nil
}

// resolveHaulerDir mirrors other variable detection, but duplicated to avoid an import cycle
func resolveHaulerDir(ro *CliRootOpts) string {
	if ro != nil && ro.HaulerDir != "" {
		return ro.HaulerDir
	}
	if d := os.Getenv(consts.HaulerDir); d != "" {
		return d
	}
	home, _ := os.UserHomeDir()
	return filepath.Join(home, consts.DefaultHaulerDirName)
}
