package flags

import (
	"context"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"regexp"

	"github.com/spf13/cobra"
	"hauler.dev/go/hauler/v2/pkg/consts"
	"hauler.dev/go/hauler/v2/pkg/log"
	"hauler.dev/go/hauler/v2/pkg/store"
)

// storeIDPattern matches the full shape of a StoreID as generated by uuid.New()... e.g. "ec520cf6-e01b-4d6f-93ea-6588de0d5159"
// Short prefixes (e.g. "ec520cf6") are resolved by ResolveStoreID itself and never reach this pattern unless the lookup fails
var storeIDPattern = regexp.MustCompile(`^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$`)

type StoreRootOpts struct {
	StoreDir     string
	Retries      int
	TempOverride string
}

func (o *StoreRootOpts) AddFlags(cmd *cobra.Command) {
	pf := cmd.PersistentFlags()
	pf.StringVarP(&o.StoreDir, "store", "s", "", "Set the directory to use for the content store")
	pf.IntVarP(&o.Retries, "retries", "r", consts.DefaultRetries, "Set the number of retries for operations")
	pf.StringVarP(&o.TempOverride, "tempdir", "t", "", "(Optional) Override the default temporary directory determined by the OS")
}

func (o *StoreRootOpts) Store(ctx context.Context, ro *CliRootOpts) (*store.Layout, error) {
	l := log.FromContext(ctx)

	haulerDir := resolveHaulerDir(ro)

	storeDir := o.StoreDir

	if storeDir == "" {
		storeDir = os.Getenv(consts.HaulerStoreDir)
	}

	if storeDir == "" {
		storeDir = consts.DefaultStoreName
	}

	// If storeDir doesn't exist as a path, see if it's a StoreID registered from a previous run elsewhere
	if _, err := os.Stat(storeDir); errors.Is(err, os.ErrNotExist) {
		id, resolved, rerr := store.ResolveStoreID(haulerDir, storeDir)
		switch {
		case rerr == nil:
			if !store.MatchesStoreID(resolved, id) {
				return nil, fmt.Errorf("store id %q was last seen at %s, but that path no longer contains that store", storeDir, resolved)
			}
			l.Debugf("resolved store id [%s] to [%s]", storeDir, resolved)
			storeDir = resolved
		case storeIDPattern.MatchString(storeDir):
			// looks like an ID, not a directory name to create
			return nil, fmt.Errorf("no store found matching id %q (for directories, use the absolute path)", storeDir)
		}
	}

	abs, err := filepath.Abs(storeDir)
	if err != nil {
		return nil, err
	}

	o.StoreDir = abs

	l.Debugf("using store at [%s]", abs)

	if _, err := os.Stat(abs); errors.Is(err, os.ErrNotExist) {
		if err := os.MkdirAll(abs, os.ModePerm); err != nil {
			return nil, err
		}
	} else if err != nil {
		return nil, err
	}

	s, err := store.NewLayout(abs, store.WithHaulerDir(haulerDir))
	if err != nil {
		return nil, err
	}
	l.Debugf("generated store id of [%s]", s.StoreID)
	return s, nil
}

// resolveHaulerDir mirrors other variable detection, but duplicated to avoid an import cycle
func resolveHaulerDir(ro *CliRootOpts) string {
	if ro != nil && ro.HaulerDir != "" {
		return ro.HaulerDir
	}
	if d := os.Getenv(consts.HaulerDir); d != "" {
		return d
	}
	home, _ := os.UserHomeDir()
	return filepath.Join(home, consts.DefaultHaulerDirName)
}
