// Code generated by "stringer -type=OutputFormat"; DO NOT EDIT.

package app

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownFormat-0]
	_ = x[TarGz-2]
	_ = x[Tar-1]
}

const _OutputFormat_name = "UnknownFormatTarTarGz"

var _OutputFormat_index = [...]uint8{0, 13, 16, 21}

func (i OutputFormat) String() string {
	if i < 0 || i >= OutputFormat(len(_OutputFormat_index)-1) {
		return "OutputFormat(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OutputFormat_name[_OutputFormat_index[i]:_OutputFormat_index[i+1]]
}
