name: Vulnerability Scan Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - release/*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  vulnerability-scan:
    name: Vulnerability Scan
    uses: ./.github/workflows/vulnerability-scan.yaml
